name: Output informatin
on: [workflow_dispatch]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: | 
                echo "${{ toJson(github) }}"   #this is an expresion 
                echo "ENV = ${{toJson(env)}}"